2주차
haedal-study/self-learning-comp-archi pull request #15
Opened 2023-08-06 14:46 UTC by weweweme

2023-08-13 13:22 UTC, ChoiSeonMun commented on weweweme/2주차.md
> + <img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FCbBb9%2FbtqUvDDBxH1%2FieF1PJ4JVqFNGtKMqLYpDk%2Fimg.png" alt="기계어와 어셈블리 어">
img 닫는 슬래시가 없습니다.

2023-08-13 13:26 UTC, ChoiSeonMun commented on weweweme/2주차.md
1. 글 구성이 굉장히 애매합니다. 문단을 작성할 거라면 제대로 작성하고, 아니라면 전처럼 Bullet Point로 작성하는 게 좋습니다. 현재의 글은 애매한 구성으로 외려 가독성이 떨어집니다.

2023-08-13 13:27 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +<img src="https://d8it4huxumps7.cloudfront.net/uploads/images/64b145126a0e8_1.jpg" alt="컴파일러와 인터프리터의 차이점">
위에 나와 있는 문단의 내용과 이미지가 매치되지 않기 때문에 이미지가 동떨어진 느낌을 받습니다.

2023-08-13 13:27 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +[이미지 출처](https://unstop.com/blog/difference-between-compiler-and-interpreter)
출처 표기는 각주를 달아서 표기를 하는 것이 좋아보입니다.

2023-08-13 13:28 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +> ex. 유니티 프로젝트 내부의 Resources 폴더를 이용하여 에셋을 관리하는 상황
예시가 부적절합니다.

2023-08-13 13:28 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +> ex. AssetBundles을 이용해 에셋을 별도의 패키지로서 동적으로 관리하는 상황
예시가 부적절합니다.

2023-08-13 13:29 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +데이터 자체보다 데이터가 저장된 위치가 적혀있으며, 메모리 주소 또는 레지스터가 적혀있습니다
'적혀 있다' 동어 반복입니다.

2023-08-13 13:31 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +> 아래와 같이, 연산을 알파벳 기호로 표기한 것을 [니모닉스(mnemonics)](https://en.wikipedia.org/wiki/Mnemonic)라고 하며, 니모닉스란 인간이 기억하기 쉬운 형태로 이름을 나타내는 기호를 뜻합니다
니모닉도 같이 정리한 건 좋은데, 그냥 `니모닉`이라고 쓰면 됩니다. 뒤에 복수 표기는 뺍니다.

2023-08-13 13:32 UTC, ChoiSeonMun commented on weweweme/2주차.md
2. 쉼표가 과하게 많습니다. 쉼표는 독자로 하여금 어떤 긴 문장이 있을 때, 가독성을 높이기 위해 사용하는데 과하게 사용하면 외려 가독성이 떨어집니다.

2023-08-13 13:34 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +하지만 레지스터 크기에 제한이 있기 때문에, 데이터의 크기에 제한이 생길 수 있습니다
레지스터 크기에 제한이 있다는 것이 무슨 얘기인가요 ?

2023-08-13 13:35 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +> MOV AX, BX
한 줄로 보여서 가독성이 떨어집니다.

2023-08-13 13:36 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +메모리에 저장된 유효 주소에 접근하여 한번 더 유효 주소를 통해 필요한 데이터가 저장된 메모리로 향하는 간접 주소 지정 방식과 비슷하지만, 레지스터에 접근하는 것이 CPU 입장에서는 빠르기 때문에, 레지스터 간접 주소 지정 방식은 간접 주소 지정 방식보다 빠릅니다
발화하며 읽어보면 문장이 굉장히 어렵다는 걸 느낄 수 있습니다. 문장을 적절하게 나누든, 표현을 바꾸든 다르게 작성하는 것이 필요합니다.

2023-08-13 13:38 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +오퍼랜드 필드에 프로그램 카운터(program counter; PC)와의 상대적인 거리 또는 오프셋(offset)을 지정하는 방식이며, 이 오프셋은 PC에 더해져서 실제 유효 주소를 얻습니다
```suggestion
오퍼랜드 필드에 프로그램 카운터(PC; program counter)와의 상대적인 거리 또는 오프셋(offset)을 지정하는 방식이며, 이 오프셋은 PC에 더해져서 실제 유효 주소를 얻습니다
```

두문어를 앞에 씁니다.

2023-08-13 13:39 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +- [Types of Addressing Modes](https://cstaleem.com/types-of-addressing-modes)
여기 자료 아무 것도 없던데요 ?

2023-08-13 13:43 UTC, ChoiSeonMun requested changes
1. 글의 구성이 애매합니다. 문단으로 확실하게 표현하지 않아 글을 읽는데 뚝뚝 흐름이 끊깁니다. 차라리 이전 Bullet Point 형식으로 정리하는 것이 좋아보입니다.
2. 과도한 쉼표 사용은 가독성을 해칩니다. 쉼표의 목적은 독자로 하여금 일종의 끊는 지점으로 작용해 글의 이해를 돕는 역할입니다. 하지만 과도하게 쉼표가 사용되어 1번과 마찬가지로 글의 흐름이 뚝뚝 끊깁니다.

2023-08-13 13:43 UTC, ChoiSeonMun commented on weweweme/2주차.md
> +# **Chapter 3: 명령어**
.

2023-08-17 13:14 UTC, weweweme commented on weweweme/2주차.md
넵 수정했습니다.

2023-08-17 13:31 UTC, weweweme reviewed
체인지.

2023-08-17 13:51 UTC, ChoiSeonMun approved these changes

2023-08-17 13:54 UTC, merged