[3주차] Invidam (박한수)
haedal-study/self-learning-comp-archi pull request #27
Opened 2023-08-17 11:59 UTC by Invidam

이번주는 준비가 부족했습니다.. 양질의 정보를 드렸어야 하는데 죄송합니다..

평일에 인터럽트가 너무 발생했어요..ㅠㅠㅠ

다음부터는 주말까지 초안을 완성하여 평일에 바쁜 일이 생겨도 완성할 수 있도록 하겠습니다..

2023-08-17 12:19 UTC, Invidam commented
1. 동기 인터럽트 추가 조사
2. 인출-해석-실행 으로 조사
3. 가상 인터럽트?

2023-08-17 12:23 UTC, ChoiSeonMun requested changes
ㅎ 이번에 확실히 시간이 부족하신 게 티나네요. 다음엔 코인 오류가 없기를..

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +1. 프로그램 카운터
개행이 적용되어 있지 않습니다.

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +읽어들인 명령어를 저장한다; 이는 추후 제어장치에게 전달된다.
세미콜론 오타인 것으로 보입니다.

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +주소 버스를 통해 읽고싶은 값의 주소를 저장한다. {주소를 저장한다는 의미에서 포인터와 유사하다.}
읽기 외에도 쓰기에도 사용됩니다. 쓰기일 때는 저장할 메모리 주소가 담깁니다.

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +데이터 버스를 통해 보관하고 싶은 값을 저장한다. {값을 저장한다는 의미에서 일반 변수와 유사하다.}
`데이터 버스를 통해 보관하고 싶은 값` 이라는 의미가 모호합니다. 좀 더 분명하게 표현하는 것이 좋을 것 같습니다.

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +정해진 용도가 있는 전용 레지스터들과 달리 다양한 용도로 활용되는 레지스터이다. x86 프로세서 기준으로 `EAX, EBX, ECX, EDX, EBP, ESP,` 등이 해당된다.
작성한 예시는 Special Purpose Register입니다. GPR이 아니에요.

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +베이스 레지스터 주소 지정 방식에서 기준점이 되는 주소를 의미한다.
```suggestion
베이스 레지스터 주소 지정 방식에서 기준점이 되는 주소를 저장한다.
```

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +임시변수, 함수 복귀 주소를 비롯한 호출된 함수에 대한 정보를 저장하는 스택 공간에서 사용하는 주소 지정 방식이다. 함수 호출시 매개변수, 지역변수 등의 정보들이 스택 공간에 push되며 함수 종료시 pop된다. 함수가 종료될 때 스택포인터는 호출 이전의 주소인 리턴 어드레스를 가리키고 이를 프로그램 카운터에 저장하여 호출 이전의 주소로 돌아간다.
여담이지만 Prolog와 Epilog에 대해서도 찾아보시면 좋습니다.

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +임시변수, 함수 복귀 주소를 비롯한 호출된 함수에 대한 정보를 저장하는 스택 공간에서 사용하는 주소 지정 방식이다. 함수 호출시 매개변수, 지역변수 등의 정보들이 스택 공간에 push되며 함수 종료시 pop된다. 함수가 종료될 때 스택포인터는 호출 이전의 주소인 리턴 어드레스를 가리키고 이를 프로그램 카운터에 저장하여 호출 이전의 주소로 돌아간다.
https://learn.microsoft.com/en-us/cpp/build/prolog-and-epilog?view=msvc-170&source=recommendations

2023-08-17 12:23 UTC, ChoiSeonMun commented on Invidam/3주차.md
> +1. 입출력 장치에서 CPU에게 인터럽트 신호를 전송한다.
입출력 장치 외에도 타이머도 있습니다.

2023-08-19 06:44 UTC, Invidam commented on Invidam/3주차.md
> +정해진 용도가 있는 전용 레지스터들과 달리 다양한 용도로 활용되는 레지스터이다. x86 프로세서 기준으로 `EAX, EBX, ECX, EDX, EBP, ESP,` 등이 해당된다.
[x86 Assembly/X86 Architecture](https://www.geeksforgeeks.org/general-purpose-registers/) 를 참고하였을 때, 범용레지스터라고 이해했습니다. 또한, 초기의 AX,BX 등의 **범용 레지스터**에서 확장되어 EAX, EBX와 같은 **범용 레지스터**가 등장했다고 이해했습니다! 확인해주세요 😅

2023-08-19 09:11 UTC, Invidam commented
리뷰해주셨던 부분들 포함하여, 전반적으로 어색한 표현들을 손봤습니다.
동기 인터럽트에 대해 좀 더 조사하려고 했는데, 제조사마다 표현이 다르다는 내용 이외에 자세한 설명은 딱히 없었어요..

2023-08-29 07:59 UTC, Invidam commented
<img width="598" alt="image" src="https://github.com/haedal-study/self-learning-comp-archi/assets/71889359/24ebad1f-4164-4641-9a5f-cfd0e8bf549b">
문제가 더 커져버렸네요....
re-review 완료되면 해결 될 것 같습니다 😂

2023-08-31 12:27 UTC, ChoiSeonMun approved these changes

2023-08-31 12:29 UTC, merged